[package]
name = "calculate"
version = "0.1.0"
authors = ["Hunter Goldstein <hunter.d.goldstein@gmail.com>"]
description = "Rust library for parsing and processing arithmetic expressions"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/redox-os/calc"
repository = "https://github.com/redox-os/calc"
include = [
  "**/*.rs",
  "Cargo.toml",
]
keywords = ["math", "calculator"]
categories = ["science", "parsing"]

[lib]
name = "calc"
path = "src/lib.rs"

[[bin]]
name = "calc"
path = "src/bin.rs"
