[package]
authors = ["Hunter Goldstein <hunter.d.goldstein@gmail.com>"]
categories = [
    "science",
    "parsing",
]
description = "Rust library for parsing and processing arithmetic expressions"
homepage = "https://github.com/redox-os/calc"
include = [
    "**/*.rs",
    "Cargo.toml",
]
keywords = [
    "math",
    "calculator",
]
license-file = "LICENSE"
name = "calculate"
readme = "README.md"
repository = "https://github.com/redox-os/calc"
version = "0.4.0"

[[bin]]
name = "calc"
path = "src/bin.rs"

[dependencies]
decimal = "2.0.0"
liner = "0.4.2"

[lib]
name = "calc"
path = "src/lib.rs"
